// File generated by Antigravity using google-services.json details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGt4ejv6fjw8Ky8akmdchEL-63cqlKQo',
    appId: '1:443901648986:web:a0bfb0023dbfa2da49f863',
    messagingSenderId: '443901648986',
    projectId: 'devteampro',
    authDomain: 'devteampro.firebaseapp.com',
    storageBucket: 'devteampro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGt4ejv6fjw8Ky8akmdchEL-63cqlKQo',
    appId: '1:443901648986:android:a0bfb0023dbfa2da49f863',
    messagingSenderId: '443901648986',
    projectId: 'devteampro',
    storageBucket: 'devteampro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGt4ejv6fjw8Ky8akmdchEL-63cqlKQo',
    appId: '1:443901648986:ios:a0bfb0023dbfa2da49f863',
    messagingSenderId: '443901648986',
    projectId: 'devteampro',
    storageBucket: 'devteampro.firebasestorage.app',
    iosBundleId: 'com.arsalandev.cashbook',
  );
}
